### PR TITLE
add fetchCities method

### LINKED ISSUE #7: Create the cities reducer

### PR DESCRIPTION
**Pull request by Tresor11**

### CODE REVIEW

**Review by barackm — APPROVED** [review]
Hi @Tresor11 , 👋 

Everything is okay for me!  There is nothing else to say other than...
Congratulations! 🎉  🎉 🎉  😄  😄

**Comment by Tresor11** [comment]
> Hi @Tresor11 , wave
> # STATUS: Approved tada
> 
> Everything is okay for me! There is nothing else to say other than...
> Congratulations! tada tada tada smile smile
> 
>

**Comment by Tresor11** [comment]
> ## Thanks @barackm  let's wait for @cedricbahirwe  approval before Merge

**Review by cedricbahirwe — COMMENTED** [review]
Everything looks fine ☺️, I think, I love the structure btw, Well done @Tresor11
> Some code commenting might really be helpful in the future...

**Review by cedricbahirwe — APPROVED** [review]

**Pull request merged**
